version: '3'

services:
 observer-0:
   image: elrondnetwork/${NODE_TAG}
   ports:
     - "8080:8080"
     - "10000:37373"
   environment:
     - SHARD=0
   volumes:
     - ${STACK_FOLDER_NAME:-~/MyObservingSquad}/node-0:/data
   command: --destination-shard-as-observer=${SHARD_0} --display-name="${DISPLAY_NAME_0}"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.6

 observer-1:
   image: elrondnetwork/${NODE_TAG}
   ports:
     - "8081:8080"
     - "10001:37373"
   environment:
     - SHARD=1 
   volumes:
     - ${STACK_FOLDER_NAME:-~/MyObservingSquad}/node-1:/data
   command: --destination-shard-as-observer=${SHARD_1} --display-name="${DISPLAY_NAME_1}"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.5
 observer-2:
   image: elrondnetwork/${NODE_TAG}
   ports:
    - "8082:8080" 
    - "10002:37373"
   environment:
     - SHARD=2
   volumes:
     - ${STACK_FOLDER_NAME:-~/MyObservingSquad}/node-2:/data
   command: --destination-shard-as-observer=${SHARD_2} --display-name="${DISPLAY_NAME_2}"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.4

 observer-meta:
   image: elrondnetwork/${NODE_TAG}
   ports:
     - "8083:8080"
     - "10003:37373"
   environment:
     - SHARD=metachain
   volumes:
     - ${STACK_FOLDER_NAME:-~/MyObservingSquad}/node-metachain:/data
   command: --destination-shard-as-observer=${SHARD_M} --display-name="${DISPLAY_NAME_M}"
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.3

 proxy:
   image: elrondnetwork/${PROXY_TAG}
   ports:
     - "8079:8079"
   environment:
     - IP=10.0.0.2
   networks:
     elrond-squad:
       ipv4_address: 10.0.0.2

networks:
  elrond-squad:
    ipam:
      config:
        - subnet: 10.0.0.0/24