version: '3'

services:
  observer-0:
    image: ${IMAGE_NAME}
    ports:
      - "8080:8080"
      - "10000:37373"
    environment:
      - SHARD=0
    volumes:
      - ${OBSERVER_DIR_0}/db:/go/elrond-go/cmd/node/db
      - ${OBSERVER_DIR_0}/logs:/go/elrond-go/cmd/node/logs
      - ${OBSERVER_DIR_0}/config:/config
    command: --destination-shard-as-observer=${SHARD_0} --validator-key-pem-file=/config/observerKey_${SHARD_0}.pem --display-name="${DISPLAY_NAME_0}"
    networks:
      elrond-squad:
        ipv4_address: 10.0.0.6

  observer-1:
    image: ${IMAGE_NAME}
    ports:
      - "8081:8080"
      - "10001:37373"
    environment:
      - SHARD=1
    volumes:
      - ${OBSERVER_DIR_1}/db:/go/elrond-go/cmd/node/db
      - ${OBSERVER_DIR_1}/logs:/go/elrond-go/cmd/node/logs
      - ${OBSERVER_DIR_1}/config:/config
    command: --destination-shard-as-observer=${SHARD_1} --validator-key-pem-file=/config/observerKey_${SHARD_1}.pem --display-name="${DISPLAY_NAME_1}"
    networks:
      elrond-squad:
        ipv4_address: 10.0.0.5
  observer-2:
    image: ${IMAGE_NAME}
    ports:
      - "8082:8080"
      - "10002:37373"
    environment:
      - SHARD=2
    volumes:
      - ${OBSERVER_DIR_2}/db:/go/elrond-go/cmd/node/db
      - ${OBSERVER_DIR_2}/logs:/go/elrond-go/cmd/node/logs
      - ${OBSERVER_DIR_2}/config:/config
    command: --destination-shard-as-observer=${SHARD_2} --validator-key-pem-file=/config/observerKey_${SHARD_2}.pem --display-name="${DISPLAY_NAME_2}"
    networks:
      elrond-squad:
        ipv4_address: 10.0.0.4

  observer-meta:
    image: ${IMAGE_NAME}
    ports:
      - "8083:8080"
      - "10003:37373"
    environment:
      - SHARD=metachain
    volumes:
      - ${OBSERVER_DIR_M}/db:/go/elrond-go/cmd/node/db
      - ${OBSERVER_DIR_M}/logs:/go/elrond-go/cmd/node/logs
      - ${OBSERVER_DIR_M}/config:/config
    command: --destination-shard-as-observer=${SHARD_M} --validator-key-pem-file=/config/observerKey_${SHARD_M}.pem --display-name="${DISPLAY_NAME_M}"
    networks:
      elrond-squad:
        ipv4_address: 10.0.0.3

  proxy:
    image: ${PROXY_IMAGE_NAME}
    ports:
      - "8079:8079"
    environment:
      - IP=10.0.0.2
    networks:
      elrond-squad:
        ipv4_address: 10.0.0.2

networks:
  elrond-squad:
    ipam:
      config:
        - subnet: 10.0.0.0/24